package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class RequestServicesJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    private UserAccount userAccount;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public RequestServicesJPanel(JPanel userProcessContainer, Enterprise enterprise, Network network, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.userAccount = userAccount;
        ReqVaccinesBtn.setVisible(false);
        ReqDoctorBtn.setVisible(false);
        ScheEventsBtn.setVisible(false);
        inventoryBtn.setVisible(false);

        if (enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Hospital")) {
            ReqVaccinesBtn.setVisible(true);
            ReqDoctorBtn.setVisible(true);
            ScheEventsBtn.setVisible(true);
        } else if (enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Vaccination")) {
            //valueLabel.setText(enterprise.getName());
            inventoryBtn.setVisible(true);
        } else if (enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Orphanage")) {
            ReqDoctorBtn.setVisible(true);
        }
    }
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScheEventsBtn = new javax.swing.JButton();
        ReqVaccinesBtn = new javax.swing.JButton();
        ReqDoctorBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        inventoryBtn = new javax.swing.JButton();
        enterpriseLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScheEventsBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ScheEventsBtn.setText("Schedule Events");
        ScheEventsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheEventsBtnActionPerformed(evt);
            }
        });
        add(ScheEventsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 170, -1));

        ReqVaccinesBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ReqVaccinesBtn.setText("Request Vaccines");
        ReqVaccinesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReqVaccinesBtnActionPerformed(evt);
            }
        });
        add(ReqVaccinesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 170, -1));

        ReqDoctorBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ReqDoctorBtn.setText("Request Doctor");
        ReqDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReqDoctorBtnActionPerformed(evt);
            }
        });
        add(ReqDoctorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 180, -1));

        backBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        inventoryBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        inventoryBtn.setText("Vaccination Inventory");
        inventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryBtnActionPerformed(evt);
            }
        });
        add(inventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Broadway", 1, 24)); // NOI18N
        enterpriseLabel1.setText("SERVICES AVAILABLE");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 340, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void ScheEventsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheEventsBtnActionPerformed

        RequestEventForOrphaByHosJPanel vrjp = new RequestEventForOrphaByHosJPanel(userProcessContainer, enterprise, network, userAccount);
        userProcessContainer.add("ScheduleEventsJPanel", vrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_ScheEventsBtnActionPerformed

    private void ReqVaccinesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReqVaccinesBtnActionPerformed
        // TODO add your handling code here:
        VaccineRequestJPanel vrjp = new VaccineRequestJPanel(userProcessContainer, enterprise, network, userAccount);
        userProcessContainer.add("VaccineRequestJPanel", vrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ReqVaccinesBtnActionPerformed

    private void ReqDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReqDoctorBtnActionPerformed
        // TODO add your handling code here:

        if (enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Hospital")) {

            RequestDoctorByHosJPanel vrjp = new RequestDoctorByHosJPanel(userProcessContainer, enterprise, network, userAccount);
            userProcessContainer.add("DoctorRequestByHosJPanel", vrjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else if (enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Orphanage")) {

            RequestDoctorByOrphaJPanel vrjp = new RequestDoctorByOrphaJPanel(userProcessContainer, enterprise, network, userAccount);
            userProcessContainer.add("DoctorRequestByOrgJPanel", vrjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }

    }//GEN-LAST:event_ReqDoctorBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void inventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryBtnActionPerformed
        // TODO add your handling code here:
        InventoryJPanel inventoryJPanel = new InventoryJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("InventoryJPanel", inventoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_inventoryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReqDoctorBtn;
    private javax.swing.JButton ReqVaccinesBtn;
    private javax.swing.JButton ScheEventsBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JButton inventoryBtn;
    // End of variables declaration//GEN-END:variables

}
